# Generated by Django 5.1.1 on 2025-04-17 15:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('subject', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('timing', models.CharField(max_length=50)),
                ('classroom', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='attended_classes',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='total_classes',
        ),
        migrations.AddField(
            model_name='course',
            name='semester_number',
            field=models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1),
        ),
        migrations.AddField(
            model_name='students',
            name='semester_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='CS101', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='Untitled Course', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
