# Generated by Django 4.2 on 2025-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_remove_teacher_cnic_remove_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
