# Generated by Django 4.2 on 2025-05-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
