# Generated by Django 4.2 on 2025-05-18 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_studentprofile_cnic_studentprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.studentprofile'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.studentprofile'),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
